name: FableCraft
version: '1.0-SNAPSHOT'
main: org.zycong.fableCraft.FableCraft
api-version: '1.21'
authors: [ zycong ]
description: RPG style plugin.

commands:
  itemDB:
    description: Manage the custom items in this server.
    permission: FableCraft.itemDB
    aliases:
      - idb
  resetStats:
    description: Reset the stats of the specified player.
    permission: FableCraft.resetStats
    aliases:
      - rs